export enum NotificationEvent {
  BOOKING_CREATED = 'BOOKING_CREATED',
  BOOKING_CONFIRMED = 'BOOKING_CONFIRMED',
  BOOKING_ASSIGNED = 'BOOKING_ASSIGNED',
  BOOKING_COMPLETED = 'BOOKING_COMPLETED',
  BOOKING_CANCELLED = 'BOOKING_CANCELLED',
  CHAT_MESSAGE = 'CHAT_MESSAGE',
}
